name: Build Multiplatform project
on:
  push:
    branches:
      - main
      - develop
  pull_request:

jobs:
  build-multiplatform-project:
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-20.04, macos-12, windows-2022 ]
        gradle: [ 8.3 ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '17'

      - name: Grant Permission to Execute Gradle
        run: chmod +x gradlew

      - name: Build project
        shell: bash
        run: ./gradlew assemble