name: Check code style
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  check-code-style:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '17'

      - name: Grant Permission to Execute Gradle
        run: chmod +x gradlew

      - name: Check code style
        shell: bash
        run: ./gradlew ktlintCheck