name: Publish Wiki
on:
  push:
    branches:
      - main
      - improvement/github_actions
    paths-ignore:
      - sample

concurrency:
  group: publish-wiki
  cancel-in-progress: true

jobs:
  publish-wiki:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '17'

      - name: Grant Permission to Execute Gradle
        run: chmod +x gradlew

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Generate Wiki
        run: ./gradlew :dokkaGenerate

      - name: Upload Wiki
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: ./build/dokka/html
          branch: gh_pages
          force: true